/*
    Copyright 2005, 2005 Burcu Yildiz
    Contact: burcu.yildiz@gmail.com

    This file is part of pdf2table.
    pdf2table is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.
    pdf2table is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
    You should have received a copy of the GNU General Public License
    along with pdf2table.  If not, see <http://www.gnu.org/licenses/>.
 */

import java.io.File;
import java.util.ArrayList;
import java.util.Arrays;
import pdf2xml.PDF2XML;
import java.util.List;

public class PDF2Table {
    
    public static void usage(){
        System.out.println("Usage: pdf2table <xmlpath> <pagenumbers>");
        System.out.println("    xmlpath <String> : path to the xml file generated by pdftohtml");
        System.out.println("    pagenumbers <String>   : commma seperated list of page numbers");
        System.exit(0);
    }
    
    public static void main(String[] args){
        if (args.length == 0) {
            usage();
        }
        List<Integer> pageNumbers = new ArrayList<Integer>();
        File source = null;
        source = new File(args[0]);
        if(args.length == 2){
            List<String> page_numbers = Arrays.asList(args[1].split(","));
            System.out.println(page_numbers);
            if(page_numbers.size() == 0)
                usage();
            else{
                for(String s: page_numbers) pageNumbers.add(Integer.valueOf(s));
            }
        }
        if(!source.isFile()){
            usage();
        }
        PDF2XML.convert(source.toString(),source.getParentFile().toString(), pageNumbers);
    }
}